import fs from 'fs';
import path from 'path';

// Find the Vite build folder
const distPath = path.resolve('dist');
const indexPath = path.join(distPath, 'index.html');

// Read the original index.html generated by Vite
const indexContent = fs.readFileSync(indexPath, 'utf-8');

// Define your pages and their specific social media tags
const pages = [
  {
    route: 'about', // This will map to yourwebsite.com/about
    title: 'About Us | Auvra',
    desc: 'Learn about our mission to build a permanent home for human history and traditions.',
    image: 'https://www.goauvra.com/about-preview.png',
    url: 'https://www.goauvra.com/about'
  },
  {
    route: 'institutional-access',
    title: 'Institutional Access | Auvra',
    desc: 'For museums and government bodies looking to preserve cultural heritage at scale.',
    image: 'https://www.goauvra.com/institutional-preview.png',
    url: 'https://www.goauvra.com/institutions'
  },
  {
    route: 'blog',
    title: 'Blog | Auvra',
    desc: 'Read the latest stories and updates on cultural preservation and technology.',
    image: 'https://www.goauvra.com/blog-preview.png',
    url: 'https://www.goauvra.com/blog'
  }
];

pages.forEach(page => {
  // Swap out the default tags for the page-specific ones
  let newContent = indexContent
    .replace(/<title>.*?<\/title>/g, `<title>${page.title}</title>`)
    .replace(/<meta name="description" content=".*?"\s*\/>/g, `<meta name="description" content="${page.desc}" />`)
    .replace(/<meta property="og:title" content=".*?"\s*\/>/g, `<meta property="og:title" content="${page.title}" />`)
    .replace(/<meta property="og:description" content=".*?"\s*\/>/g, `<meta property="og:description" content="${page.desc}" />`)
    .replace(/<meta property="og:image" content=".*?"\s*\/>/g, `<meta property="og:image" content="${page.image}" />`)
    .replace(/<meta property="og:url" content=".*?"\s*\/>/g, `<meta property="og:url" content="${page.url}" />`)
    .replace(/<meta name="twitter:title" content=".*?"\s*\/>/g, `<meta name="twitter:title" content="${page.title}" />`)
    .replace(/<meta name="twitter:description" content=".*?"\s*\/>/g, `<meta name="twitter:description" content="${page.desc}" />`)
    .replace(/<meta name="twitter:image" content=".*?"\s*\/>/g, `<meta name="twitter:image" content="${page.image}" />`);

  // Create a folder for the specific route (e.g., dist/about)
  const dir = path.join(distPath, page.route);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Save the customized index.html inside that folder
  fs.writeFileSync(path.join(dir, 'index.html'), newContent);
  console.log(`✅ Generated dynamic SEO file for /${page.route}`);
});